version: '3.9'

services:
  celery:
    build: .
    container_name: 'celery'
    command: >
      bash -c "export C_FORCE_ROOT='true'
      && celery --app=mail.celeryapp:app worker --beat --loglevel=info"
    volumes:
      - .:/code
      - ./.env.docker:/code/.env
      - mailproject_static:/code/static/
      - mailproject_media:/code/media/
    links:
      - redis
    depends_on:
      - backend
      - redis
  db:
    restart: always
    image: postgres:14.7-alpine
    container_name: 'mail_db'
    env_file:
      - ./.env.docker
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mail_app"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: .
    container_name: 'backend_mail'
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "python manage.py collectstatic --noinput
      && python manage.py makemigrations
      && python manage.py migrate
      && gunicorn mailProject.wsgi -b :8000 --log-level=debug"
    ports:
      - '8003:8000'
    volumes:
      - ./.env.docker:/code/.env
      - mailproject_static:/code/static/
      - mailproject_media:/code/media/
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    expose:
      - '6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  mailproject_static:
  mailproject_media: