version: '3.9'

services:
  celery:
    build: .
    container_name: 'celery'
    command: >
      bash -c "export C_FORCE_ROOT='true'
      && celery --app=mail.celeryapp:app worker --beat --loglevel=info"
    volumes:
      - .:/code
      - ./.env.docker:/code/.env
    links:
      - redis
    depends_on:
      - backend
      - redis
  db:
    restart: always
    image: postgres:15.0-alpine
    container_name: mail_db
    env_file:
      - ./.env.docker
    expose:
      - '5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mail_app"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: .
    container_name: 'backend'
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "python manage.py collectstatic --noinput
      && python manage.py makemigrations
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    volumes:
      - ./.env.docker:/code/.env
  redis:
    image: redis/redis-stack:latest
    container_name: redis
    expose:
      - '6379'
    ports:
      - '9999:8001'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: